# Site settings
title: l.s
baseurl: "/ap"
url: "https://kssim.github.io"

# Author
author:
  name: Lauriely Louren√ßo
  desc: Bem vindos!!!
  email: laurielylourenco@gmail.com
  selfie: assets/img/foto.jpg

# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  facebook: Test
  flickr:
  github: https://github.com/laurielylourenco
  google_plus:
  instagram:
  keybase:
  linkedin: https://www.linkedin.com/in/kssim/ 
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter: Test
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"
